# Generated by Django 5.1.3 on 2025-11-16 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recruitment_start_date', models.DateField()),
                ('recruitment_end_date', models.DateField()),
                ('recruitment_count', models.IntegerField()),
                ('benefits', models.TextField()),
                ('mission', models.TextField()),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting'), ('recruitment_ended', 'Recruitment Ended'), ('selection_complete', 'Selection Complete')], default='recruiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(limit_choices_to={'role': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
